### ISSUE TITLE
i18n lang json vs. js

### ISSUE THREAD

**Issue by molerat619** [cretueusebiu/laravel-vue-spa#121]
Thanks for this cool setup!

When I run this, my code looks for en.js instead of en.json. So I have added .json to the import in `plugins/i18n.js`, but with the webpack configuration it will not find it because of the hash.

What am I doing wrong? Thanks in advance.

**Comment by cretueusebiu** [comment]
Are you using non install or yarn ?

**Comment by molerat619** [comment]
tbh, I am not using this whole framework but I copied the plugins, app.js and webpack config. I know that makes it hard for you to point at a certain place - but maybe you have an idea

**Comment by cretueusebiu** [comment]
You probably don't have a json loader installed so that's why it looks for .js files.

**Comment by molerat619** [comment]
Thanks for the hint, but I have webpack in version 3.11.0 which already comes with a json-loader.

**Comment by molerat619** [comment]
I got it now to load the json files, but now the problem is with the cache bust. Webpack makes the en.json file to something like `lang-en.12e2888407301a1a7dd0.js`. And then the i18n.js plugin searches for it in `http://localhost/js/lang-en.12e2888407301a1a7dd0.js` instead of `http://localhost/project-name/public/js/lang-en.12e2888407301a1a7dd0.js`. Any idea why he does not look for the right folder?

**Comment by cretueusebiu** [comment]
Check the [output](https://github.com/cretueusebiu/laravel-vue-spa/blob/master/webpack.mix.js#L46) option.

**Comment by cretueusebiu** [comment]
That's because this configuration is for Laravel where you have the root folder but the domain points to the public folder. In your case you're accessing it with the project folder in the url. 

Try using something like Valet, that will give you a domain for your project that will point directly to the public directory, or adjust the publicPath, but you'll run into issue when you deploy, because I'm sure there the domain will point to the public directory.

**Comment by molerat619** [comment]
Good answer, thank you.
