### ISSUE TITLE
Route [login] not defined

### ISSUE THREAD

**Issue by JHanAlex** [cretueusebiu/laravel-vue-spa#139]
Try to navigate for /api/user when you are not login. This actions redirect you to the route with alias login, which is not declared. Error Route [login] not defined. And as I understand this is for all standard laravel named routes

**Comment by cisoun** [comment]
I'm not sure but it seems like it's a behaviour caused by the Authentificate middleware from Illuminate which is used here : https://github.com/cretueusebiu/laravel-vue-spa/blob/master/routes/api.php#L16 and which seems like to to look for a "login" named route.

Adding `->name('login')` to `Route::post('logout', 'Auth\LoginController@logout')` has solved the problem for me.

I hope it helps.

**Comment by webtamizhan** [comment]
Just add the following in web.php, If the middleware redirect to login route, it will automatically get your Vue SPA login page.
`Route::get("/login",function (){
    return view('index');
})->name('login');`
