### ISSUE TITLE
Fb and google  auth

### ISSUE THREAD

**Issue by dilovar-91** [cretueusebiu/laravel-vue-spa#158]
How to add fb and google auth?

**Comment by manu144x** [comment]
I have added Google Auth, it's fairly simple, just use check the configuration used for GitHub and you should be fine because it's still a Oauth2 standard and socialite supports all of them out of the box.

If @cretueusebiu  wants I can do a pull request and put in Google Auth support as well out of the box, (I made the component and everything too just like the github one, nothing fancy).
