### ISSUE TITLE
HMR

### ISSUE THREAD

**Issue by tiagosimoesdev** [cretueusebiu/laravel-vue-spa#163]
It seems HMR in laravel-mix is broken since last year . I can't get it to work either , anyone found a solution for this particular repo ?

**Comment by cretueusebiu** [comment]
Try this https://github.com/JeffreyWay/laravel-mix/pull/1995

**Comment by ThePjpollie** [comment]
Hey! I have also been trying a lot to get this working, I might have a potential fix.

I downgraded laravel-mix (Dev dependency) from `2.11.1` to`1.7.2`,
and removed this part from ´webpack.mix.js´ from the ´mix.webpackConfig´ object;

´´´js
  output: {
    chunkFilename: 'js/[name].[chunkhash].js',
    publicPath: mix.config.hmr ? '//localhost:8080' : '/'
  }
´´´

I have only tested this out and figured the hmr is working. I don't know if this will effect much else due to the downgrade of version & removal of that part.

**Comment by cretueusebiu** [comment]
I know for sure that with that pull request, using the latest version of mix, HMR will work. 
I'll see when I have time to patch it in this project...

**Comment by tiagosimoesdev** [comment]
Tried both but neither worked . 

I'm trying with a webpack.config.js , I'll post here if I can get it to work.

**Comment by Wiejeben** [comment]
I think your best bet is to wait until Laravel Mix uses Webpack 5. https://github.com/JeffreyWay/laravel-mix/issues/1969#issuecomment-459296379
