### ISSUE TITLE
webpack public path (generated) is wrong

### ISSUE THREAD

**Issue by h-zone** [cretueusebiu/laravel-vue-spa#173]
`npm run dev` => `public/dist/js/app.js`
```javascript
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "/";
```
look to https://github.com/JeffreyWay/laravel-mix/issues/164

better config for `webpack.mix.js` is
```
mix.webpackConfig({
  plugins: [],
  resolve: {
    extensions: ['.js', '.json', '.vue'],
    alias: {
      '~': path.join(__dirname, './resources/js')
    }
  },
  output: {
    chunkFilename: 'dist/js/[chunkhash].js',
    path: mix.config.hmr ? '/' : path.resolve(__dirname, './public/build'),
    publicPath: mix.config.hmr ? '/' : ''
  }
})
```

**Comment by h-zone** [comment]
this addition for me helps to develop standalone spa app, and i think You shoul knows about this little mistake :)

**Comment by cretueusebiu** [comment]
Did you use the code from the master branch ? Or did you install it via composer ?

What OS do you have ? I have Windows and it works as it is. Also the tests work fine on Ubuntu.

**Comment by h-zone** [comment]
This is compiled `app.js` with `npm run dev`
OS doesn't matter

I mean, the code is wrong in principle.

My addition will simply improve the outcome of your solution in such a way that it will be possible to cut out the entire front end from Laravel, and it will works fine.

**Comment by h-zone** [comment]
just relative path for generated chunks starts with '/' - absolute path, i think that this is too muchю

sory for my english.

**Comment by TemaSM** [comment]
@h-zone, as I can see, you proposed code, which already in `laravel-mix`:
https://github.com/JeffreyWay/laravel-mix/blob/ac70a860efd1f548582de97fca017d49113aa0ed/src/builder/WebpackConfig.js#L65
As I know, setting empty `publicPath` in Webpack config not good approach.
So, we not setting `publicPath` in our config, because it already set by `laravel-mix` under the hood.
Also, you reference issue which originally opened for 0.x, 1.x and 2.x versions of Laravel Mix. 
Please, use latest version of `laravel-vue-spa` from `master` branch, we are using Laravel Mix 4 (webpack 4).

Please let me know if I'm wrong, so contact me directly via Email or [Telegram](https://t.me/TemaSM), I speak Russian as well as you :)
