### ISSUE TITLE
In LoginController.php, how is ValidationException returning a json response?

### ISSUE THREAD

**Issue by aligajani** [cretueusebiu/laravel-vue-spa#202]
If I read the code, it goes like 

```
 throw ValidationException::withMessages([
            $this->username() => [trans('auth.failed')],
        ]);
```

but in reality, it doesn't seem to return a json response. However, your demo does.

**Comment by jimohalloran** [comment]
This is something the Laravel framework itself does.  It has an exception handler that is used to generate a response for an exception.  See `\Illuminate\Foundation\Exceptions\Handler::render` method that's used to do this.  Also pay particular attention to the `\Illuminate\Foundation\Exceptions\Handler::convertValidationExceptionToResponse` method which transforms the ValidationException into a response.

This is standard Laravel stuff, not unique to the `laravel-vue-spa` code base.  If you look at the Illuminate classes for authentication you'll see it throwing ValidationExceptions in order to generate error responses as well.
