### ISSUE TITLE
Could not set the layout when using ".$mount('#app')" in app.js

### ISSUE THREAD

**Issue by BashirRezaiee** [cretueusebiu/laravel-vue-spa#206]
When using 
```
new Vue({
  router,
  store,
  vuetify,
  render: h => h(App)
}).$mount('#app')
```
in the app.js file, it does not set the layout.

**Comment by jimohalloran** [comment]
It looks like all you've done is to replace the `i18n` plugin with `vuetify`, as well as changing the way the App component is rendered. 

Why not use the following instead?

```
new Vue({
  store,
  router,
  vuetify,
  ...App
})```

Note: Make sure you remove all other references to i18n, otherwise you'll cause errors elsewhere in the project.

If this doesn't help, posting more details like error messages, screenshots, etc would be helpful.

**Comment by nayils** [comment]
With this method, themes do not work. For example, "primary", etc.

**Comment by jimohalloran** [comment]
The layouts supplied with this repo are "basic" and "default", and your code fragment from `app.js` is totally different to the one in the equivelent from this repo.  See: [https://github.com/cretueusebiu/laravel-vue-spa/blob/5fffeee89d9e5aa78cd626f4e8ef7c4e2781d487/resources/js/app.js#L12](https://github.com/cretueusebiu/laravel-vue-spa/blob/5fffeee89d9e5aa78cd626f4e8ef7c4e2781d487/resources/js/app.js#L12)

Are you sure we're talking about the same project?  If so, maybe a complete non-working code sample?

**Comment by nayils** [comment]
Sorry. I'am update vuetify 2.0.

In documentation vuetify 2.0:
`new Vue({
  router,
  store,
  vuetify,
  render: h => h(App)
}).$mount('#app')`

**Comment by nayils** [comment]
The application does not have time to complete initialization and vue router does not know about setLayout functions.

**Comment by jimohalloran** [comment]
This project does not use Vuetify.  

Our `setLayout` function is part of the App component, and you've changed the way the app component is loaded/rendered with the change above.  I've never used Vuetify, but try the following:

```
new Vue({
  i18n,
  store,
  router,
  vuetify,
  ...App
})
```

Which is adding Vuetify to the code that we know works instead of replacing it with something completely different.  If you try that and you're having problems, I'd suggest you try Stack Overflow, or one of Vuetify's support resources.

**Comment by DvDty** [comment]
I was having the same issue. You should keep using `...App`, but had to add 

> This project does not use Vuetify.
> 
> Our `setLayout` function is part of the App component, and you've changed the way the app component is loaded/rendered with the change above. I've never used Vuetify, but try the following:
> 
> ```
> new Vue({
>   i18n,
>   store,
>   router,
>   vuetify,
>   ...App
> })
> ```
> 
> Which is adding Vuetify to the code that we know works instead of replacing it with something completely different. If you try that and you're having problems, I'd suggest you try Stack Overflow, or one of Vuetify's support resources.

Can confirm `...App` does work as expected with Vuetify (both v1 and v2).
