### ISSUE TITLE
Laravel mix style method did not compile css file in production enviornment.

### ISSUE THREAD

**Issue by bilal-ahmed-dev** [cretueusebiu/laravel-vue-spa#219]
Hello,
I have some custom css files which are just a plain css files, and i am linking those files in webpack.mix.js like this.

```
mix
  .js('resources/js/app.js', 'public/dist/js')
  .sass('resources/sass/app.scss', 'public/dist/css')
  .styles('resources/css/main.css', 'public/dist/css/all.css')
```

However when i have run the npm run dev command or watch its compile all.css file in above location.
But when i have run npm run production or prod command its just compile js and sass not style.

Kindly help me out what i am missing here.

Thanks Looking forward your quick response.

**Comment by jimohalloran** [comment]
I was able to reproduce the issue you had with the CSS file not being created in `public/dist/css/` in production mode.  It turns out that the file is in fact being created but the `publishAssets` function which copies the files from the` build` dir into `public/dist` deletes it.

My suggestion would be to comment out the following 3 lines of code from the `publishAssets` function:

```
  if (mix.inProduction()) {
    fs.removeSync(path.join(publicDir, 'dist'))
  }
```

Mix will no longer delete the generated CSS file in . production mode.  You'll probably want to find a different way of deleting the files in `public/dist/` before running Mix though.

**Comment by bilal-ahmed-dev** [comment]
@jimohalloran Thanks for your reply.
Also when npm run prod there are several chunk files generated in public./dist/js
I want to know that are those files required except for app.js 
If not should i remove them or not.
Sorry i am little new to this system. 

Looking forward for your reply.
Thanks

**Comment by jimohalloran** [comment]
All generated files are required.  In production mode Webpack (as configured by Laravel Mix) is splitting your code into smaller chunks that are loaded as needed.  This avoids the need to load the javascript for the entire application on first page load.
