### ISSUE TITLE
Login with username and Add a sidebar component

### ISSUE THREAD

**Issue by WichiL** [cretueusebiu/laravel-vue-spa#226]
I was trying to make login with username instead of email but i can't figure out how to do it... Also i want to add more components to the master.blade like a sidebar

**Comment by jimohalloran** [comment]
Authenticating with a username instead of email is something you'll want to do on the Laravel backend.  A quick glance at the Laravel docs suggests that [implementing a new UserProvider](https://laravel.com/docs/6.x/authentication#the-user-provider-contract) is going to be part of the solution.

You can modify the index.blade.php file and add additional components.  Bootstrap is loaded and you can use bootstrap classes to help with styling.  However, the application is really intended to be used as a single page application (SPA) with content rendered client side through Vue components.  So creating your own Vue components ad adding those to the layout is probably going to work better for you than modifying the blage template.  Take a look at the settings pages to see how they're implementing their sidebar menu.
