### ISSUE TITLE
deploy

### ISSUE THREAD

**Issue by efcjunior** [cretueusebiu/laravel-vue-spa#41]
Hi @cretueusebiu !
I appreciate your work, but I´m a question about deploy. Have I publish in web server everything in laravel-vue-spa folder ?

**Comment by cretueusebiu** [comment]
Yes, just deploy it as any other Laravel project. Just make sure to run `npm run prod` and set the env to `production`.

**Comment by dylanglockler** [comment]
To clarify, for best practice, do you 'npm run prod' then upload or upload then 'npm run prod' on the production server? It seems like the latter, with the @if (app()->isLocal()) loading only app.js and loading manifest, vendor and app in production..

**Comment by manu144x** [comment]
Normally what I do is I always push to my production server the production version.
And I always run npm run production before pushing to the remote git repository (I deploy by doing a git pull with readonly access from the server), no ftp, no sftp, none of that crap.

So I run npm run production, (i always add some other small things I need to do) and commit and push.

On the server it's only git pull and that's it.

**Comment by dylanglockler** [comment]
> So I run npm run production, (i always add some other small things I need to do) and commit and push.

That's what I was doing on other projects but with this package I believe the best practice must be to npm run dev on the local and npm run prod on the production server - I think this because the index.blade.php has app()->isLocal() mix app.js, else mix manifest, vendor, app and the gitignore excludes /public/js and /public/css, so clearly these are intended to compiled on the production server. If you want to compile on your dev then git the files to production, you'd have to make some adjustments to the gitignore.

**Comment by manu144x** [comment]
I did it that way in the past and I try to do it even now, so that I can avoid any javascript issues on the server. In the past there were always some glitches with the stupid thing, so I got used to deploying everything javascript .css to the git ready to go.

Then using multiple branches, and the master was always production ready, and have other branches for testing, staging, development, all this stuff. 

If you don't have issues it's perfectly fine even that way, I don't see an issue if finally webpack and all the javascript dependency hell is more stable so you can compile them with no issues everytime.

My issue was that if something went wrong during compiling on the production server, the entire production app was down since it was a JS app. Big risk. If I checkout from git everything ready to go, I don't have that risk at all.
