### ISSUE TITLE
running in a subdirectory

### ISSUE THREAD

**Issue by vollyimnetz** [cretueusebiu/laravel-vue-spa#93]
Hi,
i want to setup the system in a localhost subdirectory, i.e. "http://localhost/spa-test".
It will not run cause the js-import pathes are wrong. So i added a base-tag to get the imports right.
```
<html lang="{{ app()->getLocale() }}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <title>{{ config('app.name') }}</title>
  <base href="{{ url('/') }}/" />

  <link rel="stylesheet" href=".{{ mix('css/app.css') }}">
</head>
<body>
  <div id="app"></div>

  {{-- Global configuration object --}}
  <script>window.config = @json($config);</script>

  {{-- Polyfill JS features via polyfill.io --}}
  <script src="https://cdn.polyfill.io/v2/polyfill.min.js?features={{ implode(',', $polyfills) }}"></script>

  {{-- Load the application scripts --}}
  @if (app()->isLocal())
    <script src=".{{ mix('js/app.js') }}"></script>
  @else
    <script src=".{{ mix('js/manifest.js') }}"></script>
    <script src=".{{ mix('js/vendor.js') }}"></script>
    <script src=".{{ mix('js/app.js') }}"></script>
  @endif
</body>
</html>
```

All files except of 2 are included correctly:
/js/lang-en.592895da306250f00312.js
/js/5.104c057cd2770b252dfe.js

Seems to have something to do with the i18n. Webpack is running in devmode.

**How can i setup the system correctly to run in an sudirectory?**

**Comment by cretueusebiu** [comment]
You might want to customize the `chunkFilename` option in your webpack configuration. See [webpack.mix.js](https://github.com/cretueusebiu/laravel-vue-spa/blob/master/webpack.mix.js#L47).

**Comment by vollyimnetz** [comment]
Thank you, i will have a look on it.

**Comment by g011um** [comment]
My apologies for commenting on a closed issue; I can open a new one if that's preferred.

I too am looking at running this from a subdirectory in the same way @vollyimnetz suggested.  I've modified `webpack.mix.js` to include `output.publicPath` as suggested, and tweaked `index.blade.php` to add `asset()` around the existing `mix('dist/css/app.css')` and `mix('dist/js/app.js')`.  That seems to have fixed a number of issues.

However, the paths used for the Axios/API calls all seem to be hard coded to `/api/...`.  [Line 81 of `resources/js/pages/auth/login.vue`](https://github.com/cretueusebiu/laravel-vue-spa/blob/c6fab6a6a587609fd5308ec536b262df62482d5e/resources/js/pages/auth/login.vue#L81) for example:

`const { data } = await this.form.post('/api/login')`

I assume the only way to correct this is to manually update these API paths?  I'm wondering if it's safe to just remove the leading `/`, or whether that may have additional issues later with them being a relative URL?

Any chance of having these API paths prepended with some global variable or config value so that it could be set in one location, and work for everyone, regardless of whether or not they are running this SPA app from the root or a subdirectory?

**Comment by cretueusebiu** [comment]
You can set a base url with axios [default config](https://github.com/axios/axios#config-defaults):

`axios.defaults.baseURL = 'https://api.example.com'`

Or with the [interceptor](https://github.com/axios/axios#interceptors) from `resources/js/plugins/axios.js`.

**Comment by hassekf** [comment]
ps: sorry for bumping the issue, but

had the same issue, solved by adding 

`publicPath: mix.config.hmr ? '/subfolder/' : ''`

within mix.output (below webpack.mix.js:32)

And that did the trick for me (also enclosing mix assets in the view with asset())
