### ISSUE TITLE
Uncaught (in promise) Error

### ISSUE THREAD

**Issue by yusren** [cretueusebiu/laravel-vue-spa#97]
Hi cretueusebiu, 
First of all, I'm a VueJS newbie. Just wanna ask about this errror.
`Uncaught (in promise) Error: Request failed with status code 422`
`    at createError (createError.js?16d0:16)`
`    at settle (settle.js?db52:18)`
`    at XMLHttpRequest.handleLoad (xhr.js?ec6c:77)`
I know that 422 sended by Laravel Form Validator and the form showing errors like it should.
Is this normal to have the promise error status in the browser console?
I'm trying to catch the axios error, the promise error is gone, but then the form going to silent.
Sory for my bad English, and thanks for your attention.

**Comment by cretueusebiu** [comment]
I usually don't catch all exceptions.

For example:

```javascript
const { data } = await this.form.post('/api/login')

// do something with data
```
If the login fails the rest of the code won't be executed because an exception is thrown.

What you can do is:

```javascript
try {
  const { data } = await this.form.post('/api/login')

  // do something with data
} catch (e) {
  
}
```

When you just don't want the next code after the request to be executed in case of an error I prefer to not catch the exception.

If you don't want those errors just try/catch every request individually, not with an axios interceptor, since that will stop the `vform` plugin from parsing the errors.

**Comment by yusren** [comment]
I see.
Then I'll follow your Laravel-VueJS SPA way.
Thanks Sir
